Add address property
adafruit/Adafruit_CircuitPython_DS18X20 pull request #29
Opened 2024-01-12 17:56 UTC by ilikecake

Added a read-only address property to the class. This might be helpful to identify sensors if you have multiple on the bus.

2024-01-17 19:08 UTC, tannewt requested changes
Thanks! One suggestion.

2024-01-17 19:08 UTC, tannewt commented on adafruit_ds18x20.py
> +        the bus.
```suggestion
        """The address of the device. Useful if there are multiple sensors on the bus.
```

2024-01-27 17:10 UTC, ilikecake commented
I have updated the code with the requested change. Do I need to do something to resolve the change request?

2024-01-29 00:05 UTC, FoamyGuy approved these changes
Looks good, requested change was handled in the latest commit.

Thank you @ilikecake!

2024-01-29 00:05 UTC, merged